[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
description = ""

[tool.poetry.dependencies]
pandas = "*"
python = "^3.8"
scipy = "*"
matplot = "0.1.9"
matplotlib = "^3.7.2"
